
# Language/versions
language: node_js
node_js:
 - 0.8
 - 0.6

# Build script
script: './node_modules/.bin/jake -f ./jakefile.coffee ci'

# Branch whitelist
branches:
 only:
   - master

# Notifications
notifications:
 email:
   - notify+jemima@rowanmanning.co.uk
